name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - lib/bs62/version.rb

permissions:
  contents: write
  pull-requests: write

jobs:
  ruby:
    uses: yettoapp/actions/.github/workflows/ruby_gem_release.yml@main
    secrets:
      rubygems_api_key: ${{ secrets.RUBYGEMS_API_BOT_KEY }}
      gh_token: ${{ secrets.PUBLIC_PUSH_TO_PROTECTED_BRANCH }}
    with:
      gem_name: bs62
      version_filepath: lib/bs62/version.rb
      oxidized: true
